### ISSUE TITLE
Different commits shown with tags swapped the other way round

### ISSUE THREAD

**Issue by simondobson** [slapresta/cremita#5] opened 2016-06-15 13:54 UTC
Cremita shows different commits depending on which way round the tags are posted.

See screenshot
![screen shot 2016-06-15 at 15 48 03](https://cloud.githubusercontent.com/assets/18551266/16082331/35b05ff2-3311-11e6-82ec-61e148dba257.png)

**Comment by slapresta** [comment] 2016-07-09 19:09
This is probably not a bug. Given a branch `foo` containing commits `A -> B -> C` and another branch `bar` containing commits `A -> B -> D`, the comparison between `foo` and `bar` will show `C` and the reverse comparison will show `D`. When one of the comparisons is empty, cremita will reverse the identifiers for you as a courtesy, but it doesn't try both possibilities unless the first one is empty.

I'm closing this since it's hard to diagnose it as a bug without going through the git history of that repo. If you have any suggestions on how cremita should behave in these cases, feel free to reopen this and comment.

**Closed by slapresta** 2016-07-09 19:09 UTC
